# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

jobs:
  build-and-test:
    docker:
      - image: cimg/node:14.12
    steps:
      - checkout
      - run:
          name: Checkout git submodules
          command: |
            git submodule update --init --recursive
      - run:
          name: Run Core tests
          command: >-
            echo "PWD=" $(pwd) &&
            echo "CIRCLE_WORKING_DIRECTORY=" ${CIRCLE_WORKING_DIRECTORY} &&
            cd JavaScript-Core &&
            yarn install &&
            yarn test
      - run:
          name: Run Runtime tests
          command: >-
            cd JavaScript-Runtime &&
            yarn install &&
            yarn test

workflows:
  regular:
    jobs:
      - build-and-test
