# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

jobs:
  build-and-test:
    docker:
      - image: cimg/node:14.12
    steps:
      - checkout
      - run:
          name: Checkout git submodules
          command: |
            git submodule update --init --recursive
      - run:
          name: Run tests
          command: >-
            chmod 777 ./test.sh &&
            bash ./test.sh 

workflows:
  regular:
    jobs:
      - build-and-test
