env:
  browser: false
  es6: false
  node: true
  amd: true
  jest/globals: true
extends: 'eslint:recommended'
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
  Set: readonly
parser: babel-eslint
parserOptions:
  sourceType: module
plugins:
  - es5
  - jest
rules:
  no-unused-vars: ["error", {vars: "all", args: "none"}]
  no-prototype-builtins: [ "off" ]
  no-fallthrough: ["error", { "commentPattern": "no-break" }]
