env:
  browser: false
  es6: false
  node: true
  amd: true
extends: 'eslint:recommended'
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
  Set: readonly
parserOptions:
  ecmaVersion: 2018
plugins:
  - es5
rules:
  no-unused-vars: ["error", {vars: "all", args: "none"}]
  no-prototype-builtins: [ "off" ]
  no-fallthrough: ["error", { "commentPattern": "no-break" }]
